server:
  port: 7079

spring:
  elasticsearch:
    uris: http://localhost:9200

  zipkin:
    enable: true
    enable-url: http://localhost:9411
    service:
      name: elastic-service
  rabbitmq:
    host: localhost
    port: 5672
    username: socialmedia
    password: 123

rabbitmq:
  exchange-user: user-exchange
  elasticregisterkey: elastic-register-key
  queueregisterelastic: elastic-register-queue
  queueRegister: register-queue