server:
  port: 80

spring:
  zipkin:
    enable: true
    enable-url: http://localhost:9411
    service:
      name: api-gateway-service
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
      routes:
        - id: auth-service
          predicates:
            - Path=/auth/**
          uri: http://localhost:7071
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enable: true
                fallbackUri: forward:/fallback/authservice

        - id: user-service
          predicates:
            - Path=/user/**
          uri: http://localhost:7070
        - id: user-service-follow
          predicates:
            - Path=/follow/**
          uri: http://localhost:7070
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enable: true
                fallbackUri: forward:/fallback/userservice

        - id: post-service-post
          predicates:
            - Path=/post/**
          uri: http://localhost:7073
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enable: true
                fallbackUri: forward:/fallback/postservice

      default-filters:
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}
