server:
  port: 7071

spring:
  zipkin:
    enable: true
    enable-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/SocialAuthDb
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: socialmedia
    password: 123



jwt:
  secretKey: my-secret-key
  audience: socialmedia
  issuer: berkin

rabbitmq:
  exchange-auth: auth-exchange
  registerkey: register-key
  queueRegister: register-queue
  registermailkey: mail-key
  registermailqueue: mail-queue