server:
  port: 7071

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/SocialAuthDb
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secretKey: my-secret-key
  audience: socialmedia
  issuer: berkin