server:
  port: 7070

spring:
  zipkin:
    enable: true
    enable-url: http://localhost:9411
    service:
      name: user-service
  data:
    mongodb:
      host: localhost
      port: 27020
      username: java6user
      password: root
      database: userdb
  rabbitmq:
    host: localhost
    port: 5672
    username: socialmedia
    password: 123

jwt:
  secretKey: my-secret-key
  audience: socialmedia
  issuer: berkin

rabbitmq:
  exchange-auth: auth-exchange
  registerkey: register-key
  queueRegister: register-queue